// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxeXGOUCcz-5ZcsAxF4Ve9AljQhUShAg',
    appId: '1:783694751281:android:46079e805d6be431c99710',
    messagingSenderId: '783694751281',
    projectId: 'acits-prod',
    storageBucket: 'acits-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPB9JUJjuO33A-CEFKhq7Vhz_tNNxXR5A',
    appId: '1:783694751281:ios:857fc77a2eaee11ec99710',
    messagingSenderId: '783694751281',
    projectId: 'acits-prod',
    storageBucket: 'acits-prod.firebasestorage.app',
    iosBundleId: 'ru.acits',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHjx57JK1dP9tIIF6sstm27x7eRzuzuU',
    appId: '1:783694751281:web:5172d1b718fe5715c99710',
    messagingSenderId: '783694751281',
    projectId: 'acits-prod',
    authDomain: 'acits-prod.firebaseapp.com',
    storageBucket: 'acits-prod.firebasestorage.app',
  );
}
