targets:
  $default:
    sources:
      - lib/**
      - test/**
    #   - doc/api/**
      - pubspec.*
      - $package$
      # Allows the code generator to target files outside of the lib folder
      - test/integration_test/**.dart
    # builders:
    #   swagger_dart_code_generator:
    #     options:
    #       input_folder: "doc/api/"
    #       output_folder: "lib/api/"
    #       url: "https://dev.acits.ru/api"