name: acits_flutter
description: Flutter client for https://acits.ru/

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get_it: 7.2.0

  injectable: 1.5.0

  chopper: ^4.0.1

  json_annotation: ^4.1.0

  flutter_svg: 1.0.0

  intl: 0.17.0

  smooth_page_indicator: 1.0.0+2

  flutter_keyboard_visibility: 5.1.0

  shimmer: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  injectable_generator: 1.5.0

  chopper_generator: ^4.0.2

  json_serializable: ^5.0.0

  swagger_dart_code_generator: 2.2.10

  flutter_gen_runner: 4.1.3

  flutter_native_splash: 1.3.2

  build_runner: 2.1.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/onboarding/
    - assets/common/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 6d9c91e7-5307-4fce-808b-eb812e21d1fa
  class_name: StringRes
