// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxZU9UFVbDknQsqaig1XWgfOEWc73T6W4',
    appId: '1:874749050746:web:844ef9274dea161fc3a0c3',
    messagingSenderId: '874749050746',
    projectId: 'acits-dev',
    authDomain: 'acits-dev.firebaseapp.com',
    storageBucket: 'acits-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqqpKQPZmhvZCv_JEdSh1p89GOwdPqr4o',
    appId: '1:874749050746:android:d9e96dcaa51896eec3a0c3',
    messagingSenderId: '874749050746',
    projectId: 'acits-dev',
    storageBucket: 'acits-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslNQKon3Y0GiMi6hmtY2oXKPDI1S9QA8',
    appId: '1:874749050746:ios:833b35fa19c8eabdc3a0c3',
    messagingSenderId: '874749050746',
    projectId: 'acits-dev',
    storageBucket: 'acits-dev.firebasestorage.app',
    iosBundleId: 'ru.acits.dev',
  );
}
