# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

sh_flutter_build_dev="fvm flutter build ios --flavor dev -t test/dev/main.dart"

prod_scheme="prod"
dev_scheme="dev"

dev_bundle_id = "io.github.andx2"
dev_config="Release"

default_platform(:ios)

platform :ios do 

  lane :relese_dev do 

    sh sh_flutter_build_dev

    increment_build_number(
      build_number: "7" # set a specific number
    )

    increment_version_number(
      version_number: "0.0.7" # Set a specific version number
    )

    cert(
        development: false,
        api_key: get_app_store_connect_api_key
    )

    get_provisioning_profile(
      development: false,
      app_identifier: dev_bundle_id,
      api_key: get_app_store_connect_api_key
    )

    gym(
      scheme: dev_scheme,
      configuration: dev_config,
      clean: true,
      include_bitcode: false,
      export_options: {
        compileBitcode: false,
        # provisioningProfiles: {
        #     dev_bundle_id => prod_release_provision
        # }
      },
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
        skip_submission: true,
        skip_waiting_for_build_processing: true,
        api_key: get_app_store_connect_api_key
    )
  end
  
  # lane :build do |options|
  #   xcodebuild(
  #     workspace: "Runner.xcworkspace",
  #     scheme: dev_scheme,
  #     configuration: "Debug",
  #     # clean: options[:clean],
  #     build: true,
  #     destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\""
  #   )
  # end

  # lane :f_build_dev do 

  #   sh sh_flutter_build_dev
  # end

  # lane :build_app_dev do

  # end

  # lane :release do 

  #   # Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
  #   pilot
  # end



  lane :get_app_store_connect_api_key do
    # ensure_env_vars(
    #   env_vars: [
    #     'APP_STORE_CONNECT_API_KEY'
    #   ]
    # )
    # app_store_connect_api_key(
    #   key_id: "768987B394",
    #   issuer_id: "69a6de79-5741-47e3-e053-5b8c7c11a4d1",
    #   key_content: "#{ENV["APP_STORE_CONNECT_API_KEY"]}".gsub('\n', '\\n'),
    #   in_house: false,
    # )
    app_store_connect_api_key(
      key_id: "9H77DX9646",
      issuer_id: "3f2e356c-d427-4c6c-8653-3a348a52cf3b",
      key_filepath: "./fastlane/AuthKey_9H77DX9646.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
  end

end

