# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.173.0"

dev_bundle_id = "io.github.andx2.dev"
prod_bundle_id = "io.github.andx2"

dev_config = "Release-dev"
prod_config = "Release-prod"

dev_scheme = "dev"
prod_scheme = "prod"

debug_dev_provision = "certs/dev_store.mobileprovision"
prod_release_provision = "certs/prod_store.mobileprovision"

default_platform :ios

platform :ios do

  desc "Build & upload mobDev to Testflight"
  lane :releaseDev do
      release(
        app_identifier: dev_bundle_id,
        configuration: dev_config,
        scheme: dev_scheme,
        bundle_id: dev_bundle_id,
        provision: debug_dev_provision
      )
  end

  desc "Submit a new Release Build to Testflight"
  lane :release do |options|
    app_identifier = options[:app_identifier]
    configuration = options[:configuration]
    scheme = options[:scheme]
    bundle_id = options[:bundle_id]
    provision = options[:provision]

    # https://github.com/fastlane/fastlane/issues/20741
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true'

    cert(
        development: false,
        api_key: get_app_store_connect_api_key,
        output_path: "certs"
    )

    sigh(
      development: false,
      app_identifier: app_identifier,
      api_key: get_app_store_connect_api_key,
      force: true,
      filename: provision
    )

    gym(
      scheme: scheme,
      configuration: configuration,
      clean: false,
      include_bitcode: false,
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          bundle_id => provision
        }
      },
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
        skip_waiting_for_build_processing: true,
        # https://github.com/fastlane/fastlane/issues/20741
        app_identifier: app_identifier,
        api_key: get_app_store_connect_api_key
    )
  end


  lane :get_app_store_connect_api_key do
    ensure_env_vars(
      env_vars: [
        'APP_STORE_CONNECT_API_KEY'
      ]
    )
    app_store_connect_api_key(
      key_id: "9H77DX9646",
      issuer_id: "3f2e356c-d427-4c6c-8653-3a348a52cf3b",
      key_content: "#{ENV["APP_STORE_CONNECT_API_KEY"]}".gsub('\n', '\\n'),
      # key_filepath: "",
      duration: 1200,
      in_house: false,
    )
  end

end